---

- hosts: all
  vars:
    update_apt_cache: yes
  become: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml

  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
    - nginx
    - email
    - search
