---

- name: Create a staging WriteInPublic virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - application_name: writeit-live
    - debug: no
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
    - nginx
    - email
    - search
