---

- name: Provision a {{ application_name }} worker server
  hosts: workers
  become: yes
  become_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - rabbitmq
    - celery
