---

- name: Install RabbitMQ server
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - rabbitmq-server

- name: Ensure that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes
