---

- include: copy_scripts.yml

- include: setup_supervisor.yml

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  register: supervisor_applications
  tags:
    - celery
    - deploy

- name: Restart the celery worker app
  supervisorctl: name=celery_worker state=restarted
  when: supervisor_applications.stdout.find('celery_worker') != -1
  tags:
    - celery
    - deploy

- name: Restart the celery beat app
  supervisorctl: name=celery_beat state=restarted
  when: supervisor_applications.stdout.find('celery_beat') != -1
  tags:
    - celery
    - deploy
