---

- include: copy_scripts.yml

- include: setup_supervisor.yml

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  register: supervisor_applications
  tags:
    - celery
    - deploy

- name: Restart the celery apps
  supervisorctl: name=celery_{{ item }} state=restarted
  when: supervisor_applications.stdout.find('celery_{{ item }}') != -1
  tags:
    - celery
    - deploy
  with_items: "{{ celery_programs }}"
