---

- name: Install Supervisor
  apt: name=supervisor update_cache={{ update_apt_cache }} state=installed
  tags:
    - celery

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes
  tags:
    - celery

- name: Create the Supervisor config file for celery
  template: src=supervisor_celery.conf.j2
            dest=/etc/supervisor/conf.d/celery.conf
  tags:
    - celery

- name: Create the celery log directory
  file: path={{ celery_log_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=directory
  tags:
    - celery

- name: Create the celery log file
  file: path={{ celery_log_file }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
  tags:
    - celery

- name: Re-read the Supervisor config files
  command: supervisorctl reread
  tags:
    - celery

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
  tags:
    - celery
