---

- name: Create the application user
  user: name={{ gunicorn_user }} state=present

- name: Create the application group
  group: name={{ gunicorn_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ gunicorn_user }} group={{ gunicorn_group }} state=present

- name: Create the deploy user
  user: name=deploy group=sudo shell=/bin/bash

- name: Add SSH keys for deploy users
  authorized_key: user=deploy key=https://github.com/{{ item }}.keys
  with_items: "{{ deploy_github_users }}"
